/*
 * This file is generated by jOOQ.
 */
package org.db.flyway.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Levels implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  levelName;
    private Boolean active;
    private String  category;

    public Levels() {}

    public Levels(Levels value) {
        this.id = value.id;
        this.levelName = value.levelName;
        this.active = value.active;
        this.category = value.category;
    }

    public Levels(
        Integer id,
        String  levelName,
        Boolean active,
        String  category
    ) {
        this.id = id;
        this.levelName = levelName;
        this.active = active;
        this.category = category;
    }

    /**
     * Getter for <code>registration_app.levels.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>registration_app.levels.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>registration_app.levels.level_name</code>.
     */
    public String getLevelName() {
        return this.levelName;
    }

    /**
     * Setter for <code>registration_app.levels.level_name</code>.
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    /**
     * Getter for <code>registration_app.levels.active</code>.
     */
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>registration_app.levels.active</code>.
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * Getter for <code>registration_app.levels.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>registration_app.levels.category</code>.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Levels (");

        sb.append(id);
        sb.append(", ").append(levelName);
        sb.append(", ").append(active);
        sb.append(", ").append(category);

        sb.append(")");
        return sb.toString();
    }
}
