/*
 * This file is generated by jOOQ.
 */
package org.db.flyway.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipantsLevels implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer participantId;
    private Integer levelId;
    private Integer score;
    private Integer rank;
    private String  result;
    private String  custom_1;
    private String  custom_2;
    private String  custom_3;
    private String  custom_4;

    public ParticipantsLevels() {}

    public ParticipantsLevels(ParticipantsLevels value) {
        this.participantId = value.participantId;
        this.levelId = value.levelId;
        this.score = value.score;
        this.rank = value.rank;
        this.result = value.result;
        this.custom_1 = value.custom_1;
        this.custom_2 = value.custom_2;
        this.custom_3 = value.custom_3;
        this.custom_4 = value.custom_4;
    }

    public ParticipantsLevels(
        Integer participantId,
        Integer levelId,
        Integer score,
        Integer rank,
        String  result,
        String  custom_1,
        String  custom_2,
        String  custom_3,
        String  custom_4
    ) {
        this.participantId = participantId;
        this.levelId = levelId;
        this.score = score;
        this.rank = rank;
        this.result = result;
        this.custom_1 = custom_1;
        this.custom_2 = custom_2;
        this.custom_3 = custom_3;
        this.custom_4 = custom_4;
    }

    /**
     * Getter for <code>registration_app.participants_levels.participant_id</code>.
     */
    public Integer getParticipantId() {
        return this.participantId;
    }

    /**
     * Setter for <code>registration_app.participants_levels.participant_id</code>.
     */
    public void setParticipantId(Integer participantId) {
        this.participantId = participantId;
    }

    /**
     * Getter for <code>registration_app.participants_levels.level_id</code>.
     */
    public Integer getLevelId() {
        return this.levelId;
    }

    /**
     * Setter for <code>registration_app.participants_levels.level_id</code>.
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * Getter for <code>registration_app.participants_levels.score</code>.
     */
    public Integer getScore() {
        return this.score;
    }

    /**
     * Setter for <code>registration_app.participants_levels.score</code>.
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * Getter for <code>registration_app.participants_levels.rank</code>.
     */
    public Integer getRank() {
        return this.rank;
    }

    /**
     * Setter for <code>registration_app.participants_levels.rank</code>.
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * Getter for <code>registration_app.participants_levels.result</code>.
     */
    public String getResult() {
        return this.result;
    }

    /**
     * Setter for <code>registration_app.participants_levels.result</code>.
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * Getter for <code>registration_app.participants_levels.custom_1</code>.
     */
    public String getCustom_1() {
        return this.custom_1;
    }

    /**
     * Setter for <code>registration_app.participants_levels.custom_1</code>.
     */
    public void setCustom_1(String custom_1) {
        this.custom_1 = custom_1;
    }

    /**
     * Getter for <code>registration_app.participants_levels.custom_2</code>.
     */
    public String getCustom_2() {
        return this.custom_2;
    }

    /**
     * Setter for <code>registration_app.participants_levels.custom_2</code>.
     */
    public void setCustom_2(String custom_2) {
        this.custom_2 = custom_2;
    }

    /**
     * Getter for <code>registration_app.participants_levels.custom_3</code>.
     */
    public String getCustom_3() {
        return this.custom_3;
    }

    /**
     * Setter for <code>registration_app.participants_levels.custom_3</code>.
     */
    public void setCustom_3(String custom_3) {
        this.custom_3 = custom_3;
    }

    /**
     * Getter for <code>registration_app.participants_levels.custom_4</code>.
     */
    public String getCustom_4() {
        return this.custom_4;
    }

    /**
     * Setter for <code>registration_app.participants_levels.custom_4</code>.
     */
    public void setCustom_4(String custom_4) {
        this.custom_4 = custom_4;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ParticipantsLevels (");

        sb.append(participantId);
        sb.append(", ").append(levelId);
        sb.append(", ").append(score);
        sb.append(", ").append(rank);
        sb.append(", ").append(result);
        sb.append(", ").append(custom_1);
        sb.append(", ").append(custom_2);
        sb.append(", ").append(custom_3);
        sb.append(", ").append(custom_4);

        sb.append(")");
        return sb.toString();
    }
}
