/*
 * This file is generated by jOOQ.
 */
package org.db.flyway.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Participants implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  firstName;
    private String  lastName;
    private Integer age;
    private String  mobile;
    private String  mail;
    private String  category;
    private String  country;
    private String  language;
    private String  center;
    private String  rollno;

    public Participants() {}

    public Participants(Participants value) {
        this.id = value.id;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.age = value.age;
        this.mobile = value.mobile;
        this.mail = value.mail;
        this.category = value.category;
        this.country = value.country;
        this.language = value.language;
        this.center = value.center;
        this.rollno = value.rollno;
    }

    public Participants(
        Integer id,
        String  firstName,
        String  lastName,
        Integer age,
        String  mobile,
        String  mail,
        String  category,
        String  country,
        String  language,
        String  center,
        String  rollno
    ) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.mobile = mobile;
        this.mail = mail;
        this.category = category;
        this.country = country;
        this.language = language;
        this.center = center;
        this.rollno = rollno;
    }

    /**
     * Getter for <code>registration_app.participants.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>registration_app.participants.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>registration_app.participants.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>registration_app.participants.first_name</code>.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for <code>registration_app.participants.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>registration_app.participants.last_name</code>.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for <code>registration_app.participants.age</code>.
     */
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>registration_app.participants.age</code>.
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * Getter for <code>registration_app.participants.mobile</code>.
     */
    public String getMobile() {
        return this.mobile;
    }

    /**
     * Setter for <code>registration_app.participants.mobile</code>.
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * Getter for <code>registration_app.participants.mail</code>.
     */
    public String getMail() {
        return this.mail;
    }

    /**
     * Setter for <code>registration_app.participants.mail</code>.
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * Getter for <code>registration_app.participants.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>registration_app.participants.category</code>.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for <code>registration_app.participants.country</code>.
     */
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>registration_app.participants.country</code>.
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for <code>registration_app.participants.language</code>.
     */
    public String getLanguage() {
        return this.language;
    }

    /**
     * Setter for <code>registration_app.participants.language</code>.
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * Getter for <code>registration_app.participants.center</code>.
     */
    public String getCenter() {
        return this.center;
    }

    /**
     * Setter for <code>registration_app.participants.center</code>.
     */
    public void setCenter(String center) {
        this.center = center;
    }

    /**
     * Getter for <code>registration_app.participants.rollno</code>.
     */
    public String getRollno() {
        return this.rollno;
    }

    /**
     * Setter for <code>registration_app.participants.rollno</code>.
     */
    public void setRollno(String rollno) {
        this.rollno = rollno;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Participants (");

        sb.append(id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(age);
        sb.append(", ").append(mobile);
        sb.append(", ").append(mail);
        sb.append(", ").append(category);
        sb.append(", ").append(country);
        sb.append(", ").append(language);
        sb.append(", ").append(center);
        sb.append(", ").append(rollno);

        sb.append(")");
        return sb.toString();
    }
}
