/*
 * This file is generated by jOOQ.
 */
package org.db.flyway.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Runner implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private String  bDay;
    private String  mobile;
    private String  address;
    private String  gender;
    private String  race;
    private String  tshirtSize;
    private String  collectionPlace;

    public Runner() {}

    public Runner(Runner value) {
        this.id = value.id;
        this.name = value.name;
        this.bDay = value.bDay;
        this.mobile = value.mobile;
        this.address = value.address;
        this.gender = value.gender;
        this.race = value.race;
        this.tshirtSize = value.tshirtSize;
        this.collectionPlace = value.collectionPlace;
    }

    public Runner(
        Integer id,
        String  name,
        String  bDay,
        String  mobile,
        String  address,
        String  gender,
        String  race,
        String  tshirtSize,
        String  collectionPlace
    ) {
        this.id = id;
        this.name = name;
        this.bDay = bDay;
        this.mobile = mobile;
        this.address = address;
        this.gender = gender;
        this.race = race;
        this.tshirtSize = tshirtSize;
        this.collectionPlace = collectionPlace;
    }

    /**
     * Getter for <code>registration_app.runner.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>registration_app.runner.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>registration_app.runner.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>registration_app.runner.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>registration_app.runner.b_day</code>.
     */
    public String getBDay() {
        return this.bDay;
    }

    /**
     * Setter for <code>registration_app.runner.b_day</code>.
     */
    public void setBDay(String bDay) {
        this.bDay = bDay;
    }

    /**
     * Getter for <code>registration_app.runner.mobile</code>.
     */
    public String getMobile() {
        return this.mobile;
    }

    /**
     * Setter for <code>registration_app.runner.mobile</code>.
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * Getter for <code>registration_app.runner.address</code>.
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>registration_app.runner.address</code>.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for <code>registration_app.runner.gender</code>.
     */
    public String getGender() {
        return this.gender;
    }

    /**
     * Setter for <code>registration_app.runner.gender</code>.
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * Getter for <code>registration_app.runner.race</code>.
     */
    public String getRace() {
        return this.race;
    }

    /**
     * Setter for <code>registration_app.runner.race</code>.
     */
    public void setRace(String race) {
        this.race = race;
    }

    /**
     * Getter for <code>registration_app.runner.tshirt_size</code>.
     */
    public String getTshirtSize() {
        return this.tshirtSize;
    }

    /**
     * Setter for <code>registration_app.runner.tshirt_size</code>.
     */
    public void setTshirtSize(String tshirtSize) {
        this.tshirtSize = tshirtSize;
    }

    /**
     * Getter for <code>registration_app.runner.collection_place</code>.
     */
    public String getCollectionPlace() {
        return this.collectionPlace;
    }

    /**
     * Setter for <code>registration_app.runner.collection_place</code>.
     */
    public void setCollectionPlace(String collectionPlace) {
        this.collectionPlace = collectionPlace;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Runner (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(bDay);
        sb.append(", ").append(mobile);
        sb.append(", ").append(address);
        sb.append(", ").append(gender);
        sb.append(", ").append(race);
        sb.append(", ").append(tshirtSize);
        sb.append(", ").append(collectionPlace);

        sb.append(")");
        return sb.toString();
    }
}
