/*
 * This file is generated by jOOQ.
 */
package org.db.flyway;


import org.db.flyway.tables.Levels;
import org.db.flyway.tables.Participants;
import org.db.flyway.tables.ParticipantsLevels;
import org.db.flyway.tables.Runner;
import org.db.flyway.tables.records.LevelsRecord;
import org.db.flyway.tables.records.ParticipantsLevelsRecord;
import org.db.flyway.tables.records.ParticipantsRecord;
import org.db.flyway.tables.records.RunnerRecord;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * registration_app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LevelsRecord> PK_LEVEL = Internal.createUniqueKey(Levels.LEVELS, DSL.name("pk_level"), new TableField[] { Levels.LEVELS.ID }, true);
    public static final UniqueKey<ParticipantsRecord> MAIL_UNIQ = Internal.createUniqueKey(Participants.PARTICIPANTS, DSL.name("mail_uniq"), new TableField[] { Participants.PARTICIPANTS.MAIL }, true);
    public static final UniqueKey<ParticipantsRecord> MOBILE_UNIQ = Internal.createUniqueKey(Participants.PARTICIPANTS, DSL.name("mobile_uniq"), new TableField[] { Participants.PARTICIPANTS.MOBILE }, true);
    public static final UniqueKey<ParticipantsRecord> PK_PARTICIPANT = Internal.createUniqueKey(Participants.PARTICIPANTS, DSL.name("pk_participant"), new TableField[] { Participants.PARTICIPANTS.ID }, true);
    public static final UniqueKey<RunnerRecord> PK_RUNNER = Internal.createUniqueKey(Runner.RUNNER, DSL.name("pk_runner"), new TableField[] { Runner.RUNNER.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ParticipantsLevelsRecord, LevelsRecord> PARTICIPANTS_LEVELS__FK_LEVEL = Internal.createForeignKey(ParticipantsLevels.PARTICIPANTS_LEVELS, DSL.name("fk_level"), new TableField[] { ParticipantsLevels.PARTICIPANTS_LEVELS.LEVEL_ID }, Keys.PK_LEVEL, new TableField[] { Levels.LEVELS.ID }, true);
    public static final ForeignKey<ParticipantsLevelsRecord, ParticipantsRecord> PARTICIPANTS_LEVELS__FK_PARTICIPANT = Internal.createForeignKey(ParticipantsLevels.PARTICIPANTS_LEVELS, DSL.name("fk_participant"), new TableField[] { ParticipantsLevels.PARTICIPANTS_LEVELS.PARTICIPANT_ID }, Keys.PK_PARTICIPANT, new TableField[] { Participants.PARTICIPANTS.ID }, true);
}
