/*
 * This file is generated by jOOQ.
 */
package org.db.flyway;


import java.util.Arrays;
import java.util.List;

import org.db.flyway.tables.Levels;
import org.db.flyway.tables.Participants;
import org.db.flyway.tables.ParticipantsLevels;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegistrationApp extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>registration_app</code>
     */
    public static final RegistrationApp REGISTRATION_APP = new RegistrationApp();

    /**
     * The table <code>registration_app.levels</code>.
     */
    public final Levels LEVELS = Levels.LEVELS;

    /**
     * The table <code>registration_app.participants</code>.
     */
    public final Participants PARTICIPANTS = Participants.PARTICIPANTS;

    /**
     * The table <code>registration_app.participants_levels</code>.
     */
    public final ParticipantsLevels PARTICIPANTS_LEVELS = ParticipantsLevels.PARTICIPANTS_LEVELS;

    /**
     * No further instances allowed
     */
    private RegistrationApp() {
        super("registration_app", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.LEVELS_ID_SEQ,
            Sequences.PARTICIPANTS_ID_SEQ,
            Sequences.ROLL_NO_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Levels.LEVELS,
            Participants.PARTICIPANTS,
            ParticipantsLevels.PARTICIPANTS_LEVELS);
    }
}
