/*
 * This file is generated by jOOQ.
 */
package org.db.flyway;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in registration_app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>registration_app.levels_id_seq</code>
     */
    public static final Sequence<Integer> LEVELS_ID_SEQ = Internal.createSequence("levels_id_seq", RegistrationApp.REGISTRATION_APP, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>registration_app.participants_id_seq</code>
     */
    public static final Sequence<Integer> PARTICIPANTS_ID_SEQ = Internal.createSequence("participants_id_seq", RegistrationApp.REGISTRATION_APP, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
