/*
 * This file is generated by jOOQ.
 */
package org.db.flyway;


import org.db.flyway.tables.Levels;
import org.db.flyway.tables.Participants;
import org.db.flyway.tables.ParticipantsLevels;


/**
 * Convenience access to all tables in registration_app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>registration_app.levels</code>.
     */
    public static final Levels LEVELS = Levels.LEVELS;

    /**
     * The table <code>registration_app.participants</code>.
     */
    public static final Participants PARTICIPANTS = Participants.PARTICIPANTS;

    /**
     * The table <code>registration_app.participants_levels</code>.
     */
    public static final ParticipantsLevels PARTICIPANTS_LEVELS = ParticipantsLevels.PARTICIPANTS_LEVELS;
}
