/*
 * This file is generated by jOOQ.
 */
package org.db.flyway.tables.records;


import org.db.flyway.tables.ParticipantsLevels;
import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipantsLevelsRecord extends TableRecordImpl<ParticipantsLevelsRecord> implements Record9<Integer, Integer, Integer, Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>registration_app.participants_levels.participant_id</code>.
     */
    public void setParticipantId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>registration_app.participants_levels.participant_id</code>.
     */
    public Integer getParticipantId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>registration_app.participants_levels.level_id</code>.
     */
    public void setLevelId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>registration_app.participants_levels.level_id</code>.
     */
    public Integer getLevelId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>registration_app.participants_levels.score</code>.
     */
    public void setScore(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>registration_app.participants_levels.score</code>.
     */
    public Integer getScore() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>registration_app.participants_levels.rank</code>.
     */
    public void setRank(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>registration_app.participants_levels.rank</code>.
     */
    public Integer getRank() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>registration_app.participants_levels.result</code>.
     */
    public void setResult(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>registration_app.participants_levels.result</code>.
     */
    public String getResult() {
        return (String) get(4);
    }

    /**
     * Setter for <code>registration_app.participants_levels.custom_1</code>.
     */
    public void setCustom_1(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>registration_app.participants_levels.custom_1</code>.
     */
    public String getCustom_1() {
        return (String) get(5);
    }

    /**
     * Setter for <code>registration_app.participants_levels.custom_2</code>.
     */
    public void setCustom_2(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>registration_app.participants_levels.custom_2</code>.
     */
    public String getCustom_2() {
        return (String) get(6);
    }

    /**
     * Setter for <code>registration_app.participants_levels.custom_3</code>.
     */
    public void setCustom_3(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>registration_app.participants_levels.custom_3</code>.
     */
    public String getCustom_3() {
        return (String) get(7);
    }

    /**
     * Setter for <code>registration_app.participants_levels.custom_4</code>.
     */
    public void setCustom_4(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>registration_app.participants_levels.custom_4</code>.
     */
    public String getCustom_4() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, Integer, Integer, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, Integer, Integer, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ParticipantsLevels.PARTICIPANTS_LEVELS.PARTICIPANT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ParticipantsLevels.PARTICIPANTS_LEVELS.LEVEL_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ParticipantsLevels.PARTICIPANTS_LEVELS.SCORE;
    }

    @Override
    public Field<Integer> field4() {
        return ParticipantsLevels.PARTICIPANTS_LEVELS.RANK;
    }

    @Override
    public Field<String> field5() {
        return ParticipantsLevels.PARTICIPANTS_LEVELS.RESULT;
    }

    @Override
    public Field<String> field6() {
        return ParticipantsLevels.PARTICIPANTS_LEVELS.CUSTOM_1;
    }

    @Override
    public Field<String> field7() {
        return ParticipantsLevels.PARTICIPANTS_LEVELS.CUSTOM_2;
    }

    @Override
    public Field<String> field8() {
        return ParticipantsLevels.PARTICIPANTS_LEVELS.CUSTOM_3;
    }

    @Override
    public Field<String> field9() {
        return ParticipantsLevels.PARTICIPANTS_LEVELS.CUSTOM_4;
    }

    @Override
    public Integer component1() {
        return getParticipantId();
    }

    @Override
    public Integer component2() {
        return getLevelId();
    }

    @Override
    public Integer component3() {
        return getScore();
    }

    @Override
    public Integer component4() {
        return getRank();
    }

    @Override
    public String component5() {
        return getResult();
    }

    @Override
    public String component6() {
        return getCustom_1();
    }

    @Override
    public String component7() {
        return getCustom_2();
    }

    @Override
    public String component8() {
        return getCustom_3();
    }

    @Override
    public String component9() {
        return getCustom_4();
    }

    @Override
    public Integer value1() {
        return getParticipantId();
    }

    @Override
    public Integer value2() {
        return getLevelId();
    }

    @Override
    public Integer value3() {
        return getScore();
    }

    @Override
    public Integer value4() {
        return getRank();
    }

    @Override
    public String value5() {
        return getResult();
    }

    @Override
    public String value6() {
        return getCustom_1();
    }

    @Override
    public String value7() {
        return getCustom_2();
    }

    @Override
    public String value8() {
        return getCustom_3();
    }

    @Override
    public String value9() {
        return getCustom_4();
    }

    @Override
    public ParticipantsLevelsRecord value1(Integer value) {
        setParticipantId(value);
        return this;
    }

    @Override
    public ParticipantsLevelsRecord value2(Integer value) {
        setLevelId(value);
        return this;
    }

    @Override
    public ParticipantsLevelsRecord value3(Integer value) {
        setScore(value);
        return this;
    }

    @Override
    public ParticipantsLevelsRecord value4(Integer value) {
        setRank(value);
        return this;
    }

    @Override
    public ParticipantsLevelsRecord value5(String value) {
        setResult(value);
        return this;
    }

    @Override
    public ParticipantsLevelsRecord value6(String value) {
        setCustom_1(value);
        return this;
    }

    @Override
    public ParticipantsLevelsRecord value7(String value) {
        setCustom_2(value);
        return this;
    }

    @Override
    public ParticipantsLevelsRecord value8(String value) {
        setCustom_3(value);
        return this;
    }

    @Override
    public ParticipantsLevelsRecord value9(String value) {
        setCustom_4(value);
        return this;
    }

    @Override
    public ParticipantsLevelsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParticipantsLevelsRecord
     */
    public ParticipantsLevelsRecord() {
        super(ParticipantsLevels.PARTICIPANTS_LEVELS);
    }

    /**
     * Create a detached, initialised ParticipantsLevelsRecord
     */
    public ParticipantsLevelsRecord(Integer participantId, Integer levelId, Integer score, Integer rank, String result, String custom_1, String custom_2, String custom_3, String custom_4) {
        super(ParticipantsLevels.PARTICIPANTS_LEVELS);

        setParticipantId(participantId);
        setLevelId(levelId);
        setScore(score);
        setRank(rank);
        setResult(result);
        setCustom_1(custom_1);
        setCustom_2(custom_2);
        setCustom_3(custom_3);
        setCustom_4(custom_4);
    }
}
