/*
 * This file is generated by jOOQ.
 */
package org.db.flyway.tables.records;


import org.db.flyway.tables.Participants;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipantsRecord extends UpdatableRecordImpl<ParticipantsRecord> implements Record15<Integer, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>registration_app.participants.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>registration_app.participants.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>registration_app.participants.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>registration_app.participants.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>registration_app.participants.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>registration_app.participants.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>registration_app.participants.age</code>.
     */
    public void setAge(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>registration_app.participants.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>registration_app.participants.mobile</code>.
     */
    public void setMobile(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>registration_app.participants.mobile</code>.
     */
    public String getMobile() {
        return (String) get(4);
    }

    /**
     * Setter for <code>registration_app.participants.mail</code>.
     */
    public void setMail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>registration_app.participants.mail</code>.
     */
    public String getMail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>registration_app.participants.category</code>.
     */
    public void setCategory(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>registration_app.participants.category</code>.
     */
    public String getCategory() {
        return (String) get(6);
    }

    /**
     * Setter for <code>registration_app.participants.country</code>.
     */
    public void setCountry(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>registration_app.participants.country</code>.
     */
    public String getCountry() {
        return (String) get(7);
    }

    /**
     * Setter for <code>registration_app.participants.language</code>.
     */
    public void setLanguage(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>registration_app.participants.language</code>.
     */
    public String getLanguage() {
        return (String) get(8);
    }

    /**
     * Setter for <code>registration_app.participants.center</code>.
     */
    public void setCenter(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>registration_app.participants.center</code>.
     */
    public String getCenter() {
        return (String) get(9);
    }

    /**
     * Setter for <code>registration_app.participants.rollno</code>.
     */
    public void setRollno(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>registration_app.participants.rollno</code>.
     */
    public String getRollno() {
        return (String) get(10);
    }

    /**
     * Setter for <code>registration_app.participants.level1_score</code>.
     */
    public void setLevel1Score(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>registration_app.participants.level1_score</code>.
     */
    public String getLevel1Score() {
        return (String) get(11);
    }

    /**
     * Setter for <code>registration_app.participants.level2_score</code>.
     */
    public void setLevel2Score(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>registration_app.participants.level2_score</code>.
     */
    public String getLevel2Score() {
        return (String) get(12);
    }

    /**
     * Setter for <code>registration_app.participants.level3_score</code>.
     */
    public void setLevel3Score(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>registration_app.participants.level3_score</code>.
     */
    public String getLevel3Score() {
        return (String) get(13);
    }

    /**
     * Setter for <code>registration_app.participants.level4_score</code>.
     */
    public void setLevel4Score(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>registration_app.participants.level4_score</code>.
     */
    public String getLevel4Score() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Integer, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Integer, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Participants.PARTICIPANTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Participants.PARTICIPANTS.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Participants.PARTICIPANTS.LAST_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return Participants.PARTICIPANTS.AGE;
    }

    @Override
    public Field<String> field5() {
        return Participants.PARTICIPANTS.MOBILE;
    }

    @Override
    public Field<String> field6() {
        return Participants.PARTICIPANTS.MAIL;
    }

    @Override
    public Field<String> field7() {
        return Participants.PARTICIPANTS.CATEGORY;
    }

    @Override
    public Field<String> field8() {
        return Participants.PARTICIPANTS.COUNTRY;
    }

    @Override
    public Field<String> field9() {
        return Participants.PARTICIPANTS.LANGUAGE;
    }

    @Override
    public Field<String> field10() {
        return Participants.PARTICIPANTS.CENTER;
    }

    @Override
    public Field<String> field11() {
        return Participants.PARTICIPANTS.ROLLNO;
    }

    @Override
    public Field<String> field12() {
        return Participants.PARTICIPANTS.LEVEL1_SCORE;
    }

    @Override
    public Field<String> field13() {
        return Participants.PARTICIPANTS.LEVEL2_SCORE;
    }

    @Override
    public Field<String> field14() {
        return Participants.PARTICIPANTS.LEVEL3_SCORE;
    }

    @Override
    public Field<String> field15() {
        return Participants.PARTICIPANTS.LEVEL4_SCORE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public Integer component4() {
        return getAge();
    }

    @Override
    public String component5() {
        return getMobile();
    }

    @Override
    public String component6() {
        return getMail();
    }

    @Override
    public String component7() {
        return getCategory();
    }

    @Override
    public String component8() {
        return getCountry();
    }

    @Override
    public String component9() {
        return getLanguage();
    }

    @Override
    public String component10() {
        return getCenter();
    }

    @Override
    public String component11() {
        return getRollno();
    }

    @Override
    public String component12() {
        return getLevel1Score();
    }

    @Override
    public String component13() {
        return getLevel2Score();
    }

    @Override
    public String component14() {
        return getLevel3Score();
    }

    @Override
    public String component15() {
        return getLevel4Score();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public Integer value4() {
        return getAge();
    }

    @Override
    public String value5() {
        return getMobile();
    }

    @Override
    public String value6() {
        return getMail();
    }

    @Override
    public String value7() {
        return getCategory();
    }

    @Override
    public String value8() {
        return getCountry();
    }

    @Override
    public String value9() {
        return getLanguage();
    }

    @Override
    public String value10() {
        return getCenter();
    }

    @Override
    public String value11() {
        return getRollno();
    }

    @Override
    public String value12() {
        return getLevel1Score();
    }

    @Override
    public String value13() {
        return getLevel2Score();
    }

    @Override
    public String value14() {
        return getLevel3Score();
    }

    @Override
    public String value15() {
        return getLevel4Score();
    }

    @Override
    public ParticipantsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ParticipantsRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public ParticipantsRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public ParticipantsRecord value4(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public ParticipantsRecord value5(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public ParticipantsRecord value6(String value) {
        setMail(value);
        return this;
    }

    @Override
    public ParticipantsRecord value7(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public ParticipantsRecord value8(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public ParticipantsRecord value9(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public ParticipantsRecord value10(String value) {
        setCenter(value);
        return this;
    }

    @Override
    public ParticipantsRecord value11(String value) {
        setRollno(value);
        return this;
    }

    @Override
    public ParticipantsRecord value12(String value) {
        setLevel1Score(value);
        return this;
    }

    @Override
    public ParticipantsRecord value13(String value) {
        setLevel2Score(value);
        return this;
    }

    @Override
    public ParticipantsRecord value14(String value) {
        setLevel3Score(value);
        return this;
    }

    @Override
    public ParticipantsRecord value15(String value) {
        setLevel4Score(value);
        return this;
    }

    @Override
    public ParticipantsRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParticipantsRecord
     */
    public ParticipantsRecord() {
        super(Participants.PARTICIPANTS);
    }

    /**
     * Create a detached, initialised ParticipantsRecord
     */
    public ParticipantsRecord(Integer id, String firstName, String lastName, Integer age, String mobile, String mail, String category, String country, String language, String center, String rollno, String level1Score, String level2Score, String level3Score, String level4Score) {
        super(Participants.PARTICIPANTS);

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setAge(age);
        setMobile(mobile);
        setMail(mail);
        setCategory(category);
        setCountry(country);
        setLanguage(language);
        setCenter(center);
        setRollno(rollno);
        setLevel1Score(level1Score);
        setLevel2Score(level2Score);
        setLevel3Score(level3Score);
        setLevel4Score(level4Score);
    }
}
