/*
 * This file is generated by jOOQ.
 */
package org.db.flyway.tables.records;


import org.db.flyway.tables.Runner;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RunnerRecord extends UpdatableRecordImpl<RunnerRecord> implements Record9<Integer, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>registration_app.runner.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>registration_app.runner.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>registration_app.runner.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>registration_app.runner.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>registration_app.runner.b_day</code>.
     */
    public void setBDay(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>registration_app.runner.b_day</code>.
     */
    public String getBDay() {
        return (String) get(2);
    }

    /**
     * Setter for <code>registration_app.runner.mobile</code>.
     */
    public void setMobile(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>registration_app.runner.mobile</code>.
     */
    public String getMobile() {
        return (String) get(3);
    }

    /**
     * Setter for <code>registration_app.runner.address</code>.
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>registration_app.runner.address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>registration_app.runner.gender</code>.
     */
    public void setGender(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>registration_app.runner.gender</code>.
     */
    public String getGender() {
        return (String) get(5);
    }

    /**
     * Setter for <code>registration_app.runner.race</code>.
     */
    public void setRace(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>registration_app.runner.race</code>.
     */
    public String getRace() {
        return (String) get(6);
    }

    /**
     * Setter for <code>registration_app.runner.tshirt_size</code>.
     */
    public void setTshirtSize(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>registration_app.runner.tshirt_size</code>.
     */
    public String getTshirtSize() {
        return (String) get(7);
    }

    /**
     * Setter for <code>registration_app.runner.collection_place</code>.
     */
    public void setCollectionPlace(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>registration_app.runner.collection_place</code>.
     */
    public String getCollectionPlace() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Runner.RUNNER.ID;
    }

    @Override
    public Field<String> field2() {
        return Runner.RUNNER.NAME;
    }

    @Override
    public Field<String> field3() {
        return Runner.RUNNER.B_DAY;
    }

    @Override
    public Field<String> field4() {
        return Runner.RUNNER.MOBILE;
    }

    @Override
    public Field<String> field5() {
        return Runner.RUNNER.ADDRESS;
    }

    @Override
    public Field<String> field6() {
        return Runner.RUNNER.GENDER;
    }

    @Override
    public Field<String> field7() {
        return Runner.RUNNER.RACE;
    }

    @Override
    public Field<String> field8() {
        return Runner.RUNNER.TSHIRT_SIZE;
    }

    @Override
    public Field<String> field9() {
        return Runner.RUNNER.COLLECTION_PLACE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getBDay();
    }

    @Override
    public String component4() {
        return getMobile();
    }

    @Override
    public String component5() {
        return getAddress();
    }

    @Override
    public String component6() {
        return getGender();
    }

    @Override
    public String component7() {
        return getRace();
    }

    @Override
    public String component8() {
        return getTshirtSize();
    }

    @Override
    public String component9() {
        return getCollectionPlace();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getBDay();
    }

    @Override
    public String value4() {
        return getMobile();
    }

    @Override
    public String value5() {
        return getAddress();
    }

    @Override
    public String value6() {
        return getGender();
    }

    @Override
    public String value7() {
        return getRace();
    }

    @Override
    public String value8() {
        return getTshirtSize();
    }

    @Override
    public String value9() {
        return getCollectionPlace();
    }

    @Override
    public RunnerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RunnerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public RunnerRecord value3(String value) {
        setBDay(value);
        return this;
    }

    @Override
    public RunnerRecord value4(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public RunnerRecord value5(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public RunnerRecord value6(String value) {
        setGender(value);
        return this;
    }

    @Override
    public RunnerRecord value7(String value) {
        setRace(value);
        return this;
    }

    @Override
    public RunnerRecord value8(String value) {
        setTshirtSize(value);
        return this;
    }

    @Override
    public RunnerRecord value9(String value) {
        setCollectionPlace(value);
        return this;
    }

    @Override
    public RunnerRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RunnerRecord
     */
    public RunnerRecord() {
        super(Runner.RUNNER);
    }

    /**
     * Create a detached, initialised RunnerRecord
     */
    public RunnerRecord(Integer id, String name, String bDay, String mobile, String address, String gender, String race, String tshirtSize, String collectionPlace) {
        super(Runner.RUNNER);

        setId(id);
        setName(name);
        setBDay(bDay);
        setMobile(mobile);
        setAddress(address);
        setGender(gender);
        setRace(race);
        setTshirtSize(tshirtSize);
        setCollectionPlace(collectionPlace);
    }
}
